package com.polsri.union.app.util.response;

public enum ErrorCategory {
	DATA_NOT_FOUND, COMMUNICATION_FAILURE, INVALID_FORMAT, INVALID_STATE, REQUIRED_PARAMETER, AUTHORIZATION, VALIDATION_ERROR, DATA_ACCESS, UNSPECIFIED_ERROR;
}
